name: Docker Image build and push

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
      - dev
  workflow_dispatch: {}
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:

  build:

    name: Docker Image build

    runs-on: ubuntu-22.04
    timeout-minutes: 20

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Login to GCR
      uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
      with:
        registry: europe-docker.pkg.dev
        username: _json_key
        password: ${{ secrets.ARTIFACTS_REGISTRY_SERVICE_ACCOUNT }}
    - name: Build and push the Docker image
      env:
        ACTION_EVENT: ${{ github.event_name }}
      run: |
        # Duplicate standard output
        exec 5>&1 
        if [[ $ACTION_EVENT == "pull_request" ]]; then
        ./dockerImageBuild.sh -p -c 2>&1
        else
        OUTPUT=$(./dockerImageBuild.sh -p -c 2>&1 | tee /dev/fd/5; exit ${PIPESTATUS[0]})
        exit_code=$?
        exit ${exit_code}
        fi
